FROM public.ecr.aws/docker/library/golang:1.21 AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap ./cmd/lambda/

# ---

FROM public.ecr.aws/lambda/provided:al2023

COPY --from=builder /build/bootstrap ${LAMBDA_TASK_ROOT}/bootstrap
COPY config/cidr_*.json ${LAMBDA_TASK_ROOT}/config/

ENTRYPOINT ["/var/task/bootstrap"]

